### ISSUE TITLE
The format of the specified chat identifier is not supported

### ISSUE THREAD

**Issue by osama188** [stevenengland/MMM#17]
I got error 

resultOfSendText: {"isSuccess":false,"content":{"message":"An exception occured.","exceptionMessage":"The format of the specified chat identifier is not supported","exceptionType":"NotSupportedException","stackTrace":"   at StEn.MMM.Mql.Telegram.Services.Telegram.TelegramBotMapper.CreateChatId(String username)\r\n   at StEn.MMM.Mql.Telegram.Services.Telegram.TelegramBotMapper.SendText(String chatId, String text)\r\n   at StEn.MMM.Mql.Telegram.TelegramModule.SendText(String chatId, String chatText)"}}

the text I'm trying to send is simple text "this is text"

**Comment by stevenengland** [comment]
Hi Osama, sorry for coming back to you that late. The problem is with your chat id as the error tells you. Please follow the wiki and doc. If there is still a problem, tell me the format of the chat id you're using (not the original value but the format).

**Comment by stevenengland** [comment]
Further information needed. Feel free to reopen the issue if the problem and its solution is still of interested to you
